In [1]:
import numpy as np

1. Write a numpy program that creates two-dimentions array with zeroes in border

In [2]:
array = np.ones((5,5))
array[1:4, 1:4] = 0
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

2. Write a numpy program that creates a zeros border into a ones array

In [3]:
array = np.ones((3,3))
np.pad(array, 1, 'constant', constant_values=(0))

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
array = np.zeros((5,5))
array[1:4, 1:4] = 1
array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

3. Write a numpy program that converts an array with temperature values in degrees Celsius to degrees Farenheit

In [5]:
array_celsius = np.arange(15,22)
print('Array Celsius:   ', array_celsius)
array_farenheit = array_celsius * 9 / 5 + 32
print('Array Farenheit: ', array_farenheit)

Array Celsius:    [15 16 17 18 19 20 21]
Array Farenheit:  [59.  60.8 62.6 64.4 66.2 68.  69.8]


4. Write a numpy program that creates a zeroes and ones bidimentional array, generating a checkerboard pattern

In [6]:
array = np.ones((7,7))
array[::2, ::2] = 0
array_slice = array[1:7, 1:7]
array_slice[::2, ::2] = 0
array

array([[0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.]])